/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  safelist: ["-translate-y-[100%]", "translate-y-[105%]"],
  theme: {
    extend: {},
  },
  plugins: [
    require("daisyui"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/line-clamp"),
  ],
  daisyui: {
    styled: true,
    themes: [
      {
        mytheme: {
          primary: "#3457d4",
          secondary: "#463AA2",
          accent: "#F471B5",
          neutral: "#1E293B",
          "base-100": "#1d232a",
          info: "#93E7FB",
          success: "#81CFD1",
          warning: "#EFD7BB",
          error: "#E58B8B",
        },
        myThemeLight: {
          primary: "#3457d4",
          secondary: "#463aa1",
          accent: "#c149ad",
          neutral: "#021431",
          "base-100": "#FFF",
          info: "#93e6fb",
          success: "#80ced1",
          warning: "#efd8bd",
          error: "#e58b8b",
        },
        myHalloween: {
          primary: "#f28c18",
          secondary: "#f5a448",
          accent: "#187EF2",
          neutral: "#141212",
          "base-100": "#2b2b2b",
          info: "#2463eb",
          success: "#16a249",
          warning: "#db7706",
          error: "#dc2828",
        },
        myHalloweenlight: {
          primary: "#f28c18",
          secondary: "#f5a448",
          accent: "#187EF2",
          neutral: "#141212",
          "base-100": "#e4e2dd",
          info: "#2463eb",
          success: "#16a249",
          warning: "#db7706",
          error: "#dc2828",
        },
      },
      "winter",
      "bumblebee",
      "halloween",
      "lofi",
      "black",
      "cyberpunk",
      "synthwave",
      "corporate",
      "business",
    ],
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: "",
  },
};
